[package]
name = "greenring"
version = "0.1.0"
authors = ["James Uther <jbu@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = "0.4.7"
askama = "0.8"
